Feature/cadastro e login back
dedezinholindo/MC426 pull request #4
Opened 2023-09-11 23:52 UTC by dedezinholindo

adicionei a função de cadastro e login na parte do backend e uma pequena simulação pelo terminal foi adicionada pra testar o código criado

2023-09-14 12:33 UTC, IsabelaPSouza requested changes

2023-09-14 12:33 UTC, IsabelaPSouza commented on CONTRIBUTORS.md
Acho que esse arquivo tá a mais

2023-09-14 12:33 UTC, IsabelaPSouza commented on cadastro_login.py
> +@app.route('/cadastro', methods=['POST'])
cadastro tá em português e login em inglês (acho que seria bom ter um padrão)

2023-09-14 12:42 UTC, dedezinholindo commented on cadastro_login.py
> +@app.route('/cadastro', methods=['POST'])
vc diz o /login ? Acho que essa palavra ja esta meio que integrada no portugues

2023-09-14 12:43 UTC, dedezinholindo commented on CONTRIBUTORS.md
acho que pode apagar ele

2023-09-14 17:48 UTC, oallace commented on cadastro_login.py
> +@app.route('/cadastro', methods=['POST'])
Parece que os outros estão fazendo tudo em inglês, seria bom manter como padrão.

2023-09-18 00:16 UTC, IsabelaPSouza approved these changes

2023-09-18 00:23 UTC, merged